### ISSUE TITLE
Fatal exception (source file esl_buffer.c, line 1599): zero malloc disallowed

### ISSUE THREAD

**Issue by nbutyrate** [grunwaldlab/effectR#21]
Hi 

I am trying to process >900MB protein file through your tool and getting following error

i think it has something to do with Hmmerbuid, could you please review and let me know if i can do some changes in some parameters and make this work. Currently i am using 15 threads.

Creating HMM profile

Fatal exception (source file esl_buffer.c, line 1599):
zero malloc disallowed
sh: line 1: 413532 Aborted                 '/cm/shared/apps/hmmer/3.2.1/bin/hmmbuild' '--amino' '--seed' '12345' 'hmmbuild.hmm' 'MAFFT.fasta' > /dev/null

Error: File existence/permissions problem in trying to open HMM file hmmbuild.hmm.
HMM file hmmbuild.hmm not found (nor an .h3m binary of it)

HMM profile created.

Starting HMM searches

Error: File existence/permissions problem in trying to open HMM file hmmbuild.hmm.
HMM file hmmbuild.hmm not found (nor an .h3m binary of it)

hmmsearch finished!
Error in hmm.search(original.seq = fasta.file, regex.seq = REGEX, num.threads = 15) : 
  HMM failed, please supply a valid absolute path to ORFs
Execution halted

**Comment by Tabima** [comment]
Hi @nbutyrate,
The problem seems to be, as you well infer, with HMMER. It appears to be that the number of candidates via REGEX is very large and you are running out of memory (RAM) when creating the HMMER profile.

I think you might have to reduce the input dataset (not the best choice as you might not extract all the candidates from the REGEX step), use a machine with more available RAM, or export the REGEX FASTA file (using `write.fasta` from `seqinr`) and running the HMMER commands in the command line and see if you get the same error. 

Sorry I can't provide you a more elegant solution.
